### ISSUE TITLE
Default Teacher view (alpha 0.0.1)

### ISSUE THREAD

**Issue by cccons** [cccons/elle#13]
Create a default view that teachers will see upon logging in / registering / etc. Something akin to a _dashboard_ view.

**Requirements**

- [x] It shall have a link to manage exams;
- [x] It shall have a link to manage classes;
- [x] It shall have a link to manage profile data.

**Related:** #2

**Comment by cvchaparro** [comment]
Add "shortcut" links to:
- [x] Add a class;
- [x] Add an exam;
- [x] Edit user profile

**Related:** #14
